## Assessment 3 - CORRECT

This assessment is designed to give you exposure to the real-world environment of business analytics and stimulate your creativity as well as your ability to research and 
solve business problems. 

In a group of 2, you are required to investigate the dataset and create a business scenario, including questions that can help management to resolve business issues. 
You use the dataset to develop and evaluate models and develop a business case solution to address the identified questions and underlying problems.
You are asked to present this solution to the management to present them with options to resolve the addressed business problem.
 
**Packages to use:**

- `tidyverse`

**What to submit:**

1. Written report as a `.rmd` document that clearly shows all steps in data wrangling, data viz, modeling and model assessment.
2. Video presentation to stakeholders and supporting slides. Slides can be done in PowerPoint or using R tools (e.g. [`xaringam package`](https://bookdown.org/yihui/rmarkdown/xaringan.html)

**List of datasets to choose:**

*If your dataset includes several files, you do NOT nee to use ALL files. You can select one and use only one for your assignment*

[IKEA](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-11-03/readme.md)

[French Train stats](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-02-26)

[Wine ratings](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-05-28)

[Ramen rating](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-06-04)

[IKEA](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-11-03/readme.md)

[Broadway](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-04-28/readme.md)

[Pumpkin ratings](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-10-19/readme.md)

[Park access and spending](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-06-22/readme.md)

[GDPR Violations](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-04-21/readme.md)

(House and mortgage data)[https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-02-05]

[Shelters](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-12-01/readme.md)
