## Assessment 1:

**Focus**: Basic R, RMarkdown and `tidyverse` data wrangling
1. Setup your Assessment 1 project:

- Accept the invitation to work with GitHub classroom and set up this project in your RStudio as shown in class.
- create a RMarkdown document and save it in this project using assessment1.rmd
- Delete parts that you do not need in the RMarkdown template generated by default and copy the tasks below there. You need to leave the `meta data` section and initial R chunk.
- The title of your document should be Assessment 1
- The Author is your name and student id
- The date is the date you created the document

You will need to answer each task using the text/graph narration and include R chunks to show how you get them.

2 Create the heading of the first level and call it RMarkdown editing 

3. Write 2-3 sentences about RMarkdown (you can google this information or use resources recommended in class - no need to reference)

4. In the above use bold and italics for editing. 

5. Review the suggested documentation on how to insert links in the .rmd file and include an in-text link to https://rmarkdown.rstudio.com/lesson-8.html 

6. Insert an R chunk and create a variable with this dataset
https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv

The name of the variable should be `fastfood`

7. Display the first 10 rows of the dataset using head() and kable(). 

Display the first 10 rows of the dataset and the first 5 variables

Use Help and the link below to read more about those functions  https://bookdown.org/yihui/rmarkdown-cookbook/kable.html 

8. Display the observations that has more than 1000 calories

9. Arrange observations with more than 40 in total_fat and more than 80 in total_carb in the descending order and save them to a new variable (dataset) called `dont_eat_this`

10. Using the initial dataset variable, use `case_when()` to create a new variable `heavy_food` which is equal to "heavy" when total calories are greater than 500, "low" when total calories are less than 250 and "average" for all other cases. Count the number of observations in each created category.

11. Display the types of variables in the dataset using `skimr` package 

12. Present the count observations from each restaurant in a descending order

Show the number of distnct items on a menu in the dataset

13. Using groupings (group_by()), summarise and display the average number of calories for each restaurant.

14. Add variables to the dataset, which:

-  calculates the average calories per type of restaurant and call it `average_calories` 
-  calculates the maximum total_fat per type of restaurant and call it `max_fat` 
-  calculates the minimum cholesterol per type of restaurant and call it `min_cholesterol` 

15. Display the data vis of total fat per each type of restaurant. Write a narration (2-3 sentences) why you believe this type of data viz presents such information best. 

16. Add a variable to the dataset, which calculates the sum of cholesterol and sodium and call it `cholesterol_sodium`.

Remove the variable `salad`

17. Use observations for Mcdonalds to plot sugar variable against protein with `geom_point()` 


**Focus**: ggplot2, factors, strings, dates  

18. Identify variable(s) which should be factors and transform their type into a factor variable.

19. Create two new variables:

Read about `cut_number()` function using Help and add a new variable to the dataset `calories_type`. Use `calories` variable for `cut_number()` function to split it into 3 categories `n=3`, add labels `labels=c("low", "med", "high")` and make the dataset ordered by arranging it according to calories. 

Do not forget to save the updated dataset. 

20. Create a dataviz that shows the distribution of `calories_type` in food items for each type of restaurant. Think carefully about the choice of data viz. Use facets, coordinates and theme layers to make your data viz visually appealing and meaningful. Use factors related data viz functions.

21. The second variable should show the percentage of `trans_fat` in `total_fat`. Add the variable to the dataset and call it `trans_fat_percent`. Do not forget to save the updated dataset. 

22. Create a dataviz that shows the distribution of `trans_fat` in food items for each type of restaurant. Think carefully about the choice of data viz. Use facets, coordinates and theme layers to make your data viz visually appealing and meaningful.

23. Calculate and show the average (mean)  `total_fat` for each type of restaurant. No need to save it as a variable.

24. And create a dataviz that allow to compare different restaurants on this variable (`total_fat`). You can present it on one dataviz (= no facets). 

Think carefully about the choice of data viz. Use coordinates and theme layers to make your data viz visually appealing and meaningful. 

Save your file as .rmd
Pull-commit-push it to github!
